// examples/nextjs-ts-user-managment/components/ProfileCard.tsx
import { Profile } from '../lib/constants'

export default function ProfileCard({ profile }: { profile: Profile }) {
  const lastUpdated = profile.updated_at ? new Date(profile.updated_at) : null
  return (
    <div className="card">
      <p>Username: {profile.username}</p>
      <p>Website: {profile.website}</p>
      <p>
        <small>
          Last updated{' '}
          {lastUpdated
            ? `${lastUpdated.toLocaleDateString()} ${lastUpdated.toLocaleTimeString()}`
            : 'Never'}
        </small>
      </p>
    </div>
  )
}

// examples/supabase-js-v1/user-management/nuxtjs-user-management/components/ProfileCard.vue
<template>
  <div class="profileCard">
    <div class="userInfo">
      <p class="username">{{ state.propProfile.username }}</p>
      <p class="website">{{ state.propProfile.website }}</p>
      <p>
        <small>
          Last updated
          {{
            state.lastUpdated
              ? `${state.lastUpdated.toLocaleDateString()}
          ${state.lastUpdated.toLocaleTimeString()}`
              : "Never"
          }}
        </small>
      </p>
    </div>
  </div>
</template>

<script>
export default {
  props: ["profile"],
  data() {
    return {
      state: {
        propProfile: this.profile,
        lastUpdated: this.profile.updated_at
          ? new Date(this.profile.updated_at)
          : null,
      },
    };
  },
};
</script>
