// examples/todo-list/sveltejs-todo-list/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { supabase } from "$lib/db";
  import Auth from "$lib/Auth.svelte";
  import type { User } from "@supabase/supabase-js";
  import Home from "$lib/Home.svelte";

  let user: User;

  onMount(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      user = session?.user ?? null;
    });

    const { data: { subscription: authListener } } = supabase.auth.onAuthStateChange(
      (_, session) => {
        const currentUser = session?.user;
        user = currentUser ?? null;
      }
    );

    return () => {
      authListener?.unsubscribe();
    };
  });
</script>

<div class="w-full h-full bg-gray-200">
  {#if user}
    <Home bind:user />
  {:else}
    <div class="min-w-full min-h-screen flex items-center justify-center">
      <Auth />
    </div>
  {/if}
</div>

// examples/todo-vue3-ts/src/App.vue
<template>
  <div id="app" class="w-full h-full bg-gray-300">
    <div v-if="true" class="w-full h-full flex justify-center items-center p-4">
      <Auth />
    </div>
    <div v-else class="w-full h-full flex justify-center items-center p-4">
      <TodoList />
    </div>
  </div>
</template>

<script>
import Auth from '@/components/Auth.vue'
import TodoList from '@/components/TodoList.vue'
export default {
  components: {
    Auth,
    TodoList,
  },
  setup() {
    return {}
  },
}
</script>
