// blocks/vue/registry/default/social-auth/nuxtjs/app/pages/auth/error.vue
<script setup lang="ts">
import { useRoute } from "vue-router"
import { computed } from "vue"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

const route = useRoute()
const errorMessage = computed(() => route.query.error as string || null)
</script>

<template>
  <div class="flex min-h-screen w-full items-center justify-center p-6 md:p-10">
    <div class="w-full max-w-sm">
      <div class="flex flex-col gap-6">
        <Card>
          <CardHeader>
            <CardTitle class="text-2xl">Sorry, something went wrong.</CardTitle>
          </CardHeader>
          <CardContent>
            <p v-if="errorMessage" class="text-sm text-muted-foreground">
              Code error: {{ errorMessage }}
            </p>
            <p v-else class="text-sm text-muted-foreground">
              An unspecified error occurred.
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  </div>
</template>

// apps/ui-library/registry/default/blocks/passwordless-auth-tanstack/routes/auth/error.tsx
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/registry/default/components/ui/card'
import { Button } from '@/registry/default/components/ui/button'
import { Link, createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/auth/error')({
  component: AuthErrorPage,
})

function AuthErrorPage() {
  return (
    <div className="flex min-h-svh w-full items-center justify-center p-6 md:p-10">
      <div className="w-full max-w-sm">
        <Card>
          <CardHeader>
            <CardTitle className="text-2xl">Authentication Error</CardTitle>
            <CardDescription>There was an error authenticating your account</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="flex flex-col gap-4">
              <p className="text-sm text-muted-foreground">
                The authentication link may have expired or is invalid. Please try requesting a new
                one.
              </p>
              <Button asChild className="w-full">
                <Link to="/passwordless">Try again</Link>
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
