// examples/user-management/ionic-react-user-management/src/components/Avatar.tsx
import { IonIcon } from '@ionic/react'
import { person } from 'ionicons/icons'
import { Camera, CameraResultType } from '@capacitor/camera'
import { useEffect, useState } from 'react'
import { supabase } from '../supabaseClient'
import './Avatar.css'

export function Avatar({
  url,
  onUpload,
}: {
  url: string
  onUpload: (file: string) => Promise<void>
}) {
  const [avatarUrl, setAvatarUrl] = useState<string | undefined>()

  useEffect(() => {
    if (url) {
      downloadImage(url)
    }
  }, [url])

  const uploadAvatar = async () => {
    try {
      const photo = await Camera.getPhoto({
        resultType: CameraResultType.DataUrl,
      })

      const file = await fetch(photo.dataUrl!)
        .then((res) => res.blob())
        .then((blob) => new File([blob], 'my-file', { type: `image/${photo.format}` }))

      const fileName = `${Math.random()}-${new Date().getTime()}.${photo.format}`
      const { error: uploadError } = await supabase.storage.from('avatars').upload(fileName, file)
      if (uploadError) {
        throw uploadError
      }
      await onUpload(fileName)
    } catch (error) {
      console.log(error)
    }
  }

  const downloadImage = async (path: string) => {
    try {
      const { data, error } = await supabase.storage.from('avatars').download(path)
      if (error) {
        throw error
      }
      const url = URL.createObjectURL(data)
      setAvatarUrl(url)
    } catch (error: any) {
      console.log('Error downloading image: ', error.message)
    }
  }

  useEffect(() => {
    return () => {
      if (avatarUrl) {
        URL.revokeObjectURL(avatarUrl)
      }
    }
  }, [avatarUrl])

  return (
    <div className="avatar">
      <button type="button" className="avatar_wrapper" onClick={uploadAvatar}>
        {avatarUrl ? (
          <img src={avatarUrl} alt="User avatar" />
        ) : (
          <IonIcon icon={person} className="no-avatar" />
        )}
      </button>
    </div>
  )
}

// examples/user-management/ionic-angular-user-management/src/app/avatar/avatar.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';
import { SupabaseService } from '../supabase.service';
import { Camera, CameraResultType } from '@capacitor/camera';
import { addIcons } from 'ionicons';
import { person } from 'ionicons/icons';

@Component({
  selector: 'app-avatar',
  standalone: false,
  templateUrl: './avatar.component.html',
  styleUrls: ['./avatar.component.scss'],
})
export class AvatarComponent {
  _avatarUrl: SafeResourceUrl | undefined;
  uploading = false;

  @Input()
  set avatarUrl(url: string | undefined) {
    if (url) {
      this.downloadImage(url);
    }
  }

  @Output() upload = new EventEmitter<string>();

  constructor(
    private readonly supabase: SupabaseService,
    private readonly dom: DomSanitizer
  ) {
    addIcons({ person });
  }

  async downloadImage(path: string) {
    try {
      const { data, error } = await this.supabase.downLoadImage(path);
      if (error) {
        throw error;
      }
      this._avatarUrl = this.dom.bypassSecurityTrustResourceUrl(
        URL.createObjectURL(data!)
      );
    } catch (error: any) {
      console.error('Error downloading image: ', error.message);
    }
  }

  async uploadAvatar() {
    const loader = await this.supabase.createLoader();
    try {
      const photo = await Camera.getPhoto({
        resultType: CameraResultType.DataUrl,
      });

      const file = await fetch(photo.dataUrl!)
        .then((res) => res.blob())
        .then((blob) => new File([blob], 'my-file', { type: `image/${photo.format}` }));

      const fileName = `${Math.random()}-${new Date().getTime()}.${photo.format}`;

      await loader.present();
      const { error } = await this.supabase.uploadAvatar(fileName, file);

      if (error) {
        throw error;
      }

      this.upload.emit(fileName);
    } catch (error: any) {
      this.supabase.createNotice(error.message);
    } finally {
      loader.dismiss();
    }
  }
}

<div class="avatar_wrapper" (click)="uploadAvatar()">
  <img *ngIf="_avatarUrl; else noAvatar" [src]="_avatarUrl" />
  <ng-template #noAvatar>
    <ion-icon name="person" class="no-avatar"></ion-icon>
  </ng-template>
</div>
