// examples/user-management/ionic-vue-user-management/src/views/Account.vue
<template>
  <ion-page>
    <ion-header>
      <ion-toolbar>
        <ion-title>Account</ion-title>
      </ion-toolbar>
    </ion-header>

    <ion-content>
      <avatar v-model:path="profile.avatar_url" @upload="updateProfile"></avatar>
      <form @submit.prevent="updateProfile">
        <ion-item>
          <ion-label>
            <p>Email</p>
            <p>{{ email }}</p>
          </ion-label>
        </ion-item>

        <ion-item>
          <ion-input
            type="text"
            name="username"
            label="Name"
            label-placement="stacked"
            v-model="profile.username"
          ></ion-input>
        </ion-item>

        <ion-item>
          <ion-input
            type="text"
            name="website"
            label="Website"
            label-placement="stacked"
            v-model="profile.website"
          ></ion-input>
        </ion-item>
        <div class="ion-text-center">
          <ion-button fill="clear" type="submit">Update Profile</ion-button>
        </div>
      </form>

      <div class="ion-text-center">
        <ion-button fill="clear" @click="signOut">Log Out</ion-button>
      </div>
    </ion-content>
  </ion-page>
</template>

<script setup lang="ts">
import { supabase } from '@/supabase';
import {
  IonContent,
  IonHeader,
  IonPage,
  IonTitle,
  IonToolbar,
  toastController,
  loadingController,
  IonInput,
  IonItem,
  IonButton,
  IonLabel,
  useIonRouter,
} from '@ionic/vue';
import { onMounted, ref } from 'vue';
import Avatar from '../components/Avatar.vue';

const router = useIonRouter();
const email = ref('');

const profile = ref({
  username: '',
  website: '',
  avatar_url: '',
});

async function getProfile() {
  const loader = await loadingController.create({});
  const toast = await toastController.create({ duration: 5000 });
  await loader.present();
  try {
    const { data: { claims } } = await supabase.auth.getClaims();
    if (!claims) throw new Error('No user logged in');

    email.value = (claims.email as string) ?? '';

    const { data, error, status } = await supabase
      .from('profiles')
      .select(`username, website, avatar_url`)
      .eq('id', claims.sub)
      .single();

    if (error && status !== 406) throw error;

    if (data) {
      profile.value = {
        username: data.username,
        website: data.website,
        avatar_url: data.avatar_url,
      };
    }
  } catch (error: any) {
    toast.message = error.message;
    await toast.present();
  } finally {
    await loader.dismiss();
  }
}

const updateProfile = async () => {
  const loader = await loadingController.create({});
  const toast = await toastController.create({ duration: 5000 });
  try {
    await loader.present();
    const { data: { claims } } = await supabase.auth.getClaims();
    if (!claims) throw new Error('No user logged in');

    const updates = {
      id: claims.sub,
      ...profile.value,
      updated_at: new Date(),
    };

    const { error } = await supabase.from('profiles').upsert(updates);

    if (error) throw error;
  } catch (error: any) {
    toast.message = error.message;
    await toast.present();
  } finally {
    await loader.dismiss();
  }
};

async function signOut() {
  const loader = await loadingController.create({});
  const toast = await toastController.create({ duration: 5000 });
  await loader.present();
  try {
    const { error } = await supabase.auth.signOut();
    if (error) throw error;
    router.push('/', 'forward', 'replace');
  } catch (error: any) {
    toast.message = error.message;
    await toast.present();
  } finally {
    await loader.dismiss();
  }
}

onMounted(() => {
  getProfile();
});
</script>

// examples/user-management/ionic-react-user-management/src/pages/Account.tsx
import {
  IonButton,
  IonContent,
  IonHeader,
  IonInput,
  IonItem,
  IonLabel,
  IonPage,
  IonTitle,
  IonToolbar,
  useIonLoading,
  useIonToast,
  useIonRouter,
} from '@ionic/react'
import { useEffect, useState } from 'react'
import { Avatar } from '../components/Avatar'
import { supabase } from '../supabaseClient'

export function AccountPage() {
  const [showLoading, hideLoading] = useIonLoading()
  const [showToast] = useIonToast()
  const router = useIonRouter()
  const [email, setEmail] = useState('')
  const [profile, setProfile] = useState({
    username: '',
    website: '',
    avatar_url: '',
  })

  useEffect(() => {
    getProfile()
  }, [])

  const getProfile = async () => {
    await showLoading()
    try {
      const { data: authData } = await supabase.auth.getClaims()
      if (!authData?.claims) throw new Error('No user logged in')
      const { claims } = authData

      setEmail(claims.email as string)

      const { data, error, status } = await supabase
        .from('profiles')
        .select(`username, website, avatar_url`)
        .eq('id', claims.sub)
        .single()

      if (error && status !== 406) {
        throw error
      }

      if (data) {
        setProfile({
          username: data.username,
          website: data.website,
          avatar_url: data.avatar_url,
        })
      }
    } catch (error: any) {
      showToast({ message: error.message, duration: 5000 })
    } finally {
      await hideLoading()
    }
  }

  const signOut = async () => {
    await supabase.auth.signOut()
    router.push('/', 'forward', 'replace')
  }

  const updateProfile = async (e?: any, avatar_url?: string) => {
    e?.preventDefault()

    await showLoading()

    try {
      const { data } = await supabase.auth.getClaims()
      if (!data?.claims) throw new Error('No user logged in')
      const { claims } = data

      const updates = {
        id: claims.sub,
        ...profile,
        ...(avatar_url !== undefined ? { avatar_url } : {}),
        updated_at: new Date(),
      }

      const { error } = await supabase.from('profiles').upsert(updates)

      if (error) {
        throw error
      }
    } catch (error: any) {
      showToast({ message: error.message, duration: 5000 })
    } finally {
      await hideLoading()
    }
  }

  return (
    <IonPage>
      <IonHeader>
        <IonToolbar>
          <IonTitle>Account</IonTitle>
        </IonToolbar>
      </IonHeader>

      <IonContent>
        <Avatar url={profile.avatar_url} onUpload={updateProfile}></Avatar>
        <form onSubmit={updateProfile}>
          <IonItem>
            <IonLabel>
              <p>Email</p>
              <p>{email}</p>
            </IonLabel>
          </IonItem>

          <IonItem>
            <IonInput
              type="text"
              name="username"
              value={profile.username}
              onIonInput={(e) => setProfile({ ...profile, username: e.detail.value ?? '' })}
              label="Name"
              labelPlacement="stacked"
            ></IonInput>
          </IonItem>

          <IonItem>
            <IonInput
              type="url"
              name="website"
              value={profile.website}
              onIonInput={(e) => setProfile({ ...profile, website: e.detail.value ?? '' })}
              label="Website"
              labelPlacement="stacked"
            ></IonInput>
          </IonItem>
          <div className="ion-text-center">
            <IonButton fill="clear" type="submit">
              Update Profile
            </IonButton>
          </div>
        </form>

        <div className="ion-text-center">
          <IonButton fill="clear" onClick={signOut}>
            Log Out
          </IonButton>
        </div>
      </IonContent>
    </IonPage>
  )
}
