// examples/todo-vue3-ts/src/components/TodoList.vue
<template>
  <div class="w-full">
    <h1 class="mb-12 font-bold text-6xl">Todo List.</h1>
    <div class="flex gap-2 my-2">
      <input
        v-model="task"
        class="rounded w-full p-2"
        type="text"
        placeholder="What do you need to?"
      />
      <button @click="insertTask" class="btn-black">
        Add
      </button>
    </div>

    <div class="bg-white shadow overflow-hidden rounded-md">
      <ul v-for="(todo, index) in allTodos" :key="index">
        <Todo :todo="todo" />
      </ul>
    </div>
  </div>
</template>

<script lang="ts">
/* eslint-disable @typescript-eslint/camelcase */
import { defineComponent, ref } from 'vue'
import Todo from '@/components/Todo.vue'
import { allTodos, fetchTodos, addTodo } from '@/vuetils/useTodo'
import { userSession } from '@/vuetils/useAuth'

export default defineComponent({
  name: 'TodoList',
  components: {
    Todo,
  },

  async setup() {
    await fetchTodos()

    const task = ref('')

    async function insertTask() {
      if (task.value.length <= 3) {
        alert('Please make your task a little more descriptive')
        return
      }

      if (userSession?.value === null) {
        alert('Please log in again')
        return
      }

      const todo = await addTodo({ user_id: userSession.value.user.id, task: task.value })

      if (!todo) {
        return
      }

      allTodos.value.push(todo)
    }

    return {
      task,
      allTodos,
      insertTask,
      userSession,
    }
  },
})
</script>

// examples/supabase-js-v1/todo-list/sveltejs-todo-list/src/lib/TodoList.svelte
<script lang="ts">
  import type { User } from "@supabase/supabase-js";
  import Todo from "./Todo.svelte";
  import { supabase } from "./db";
  import Alert from "./Alert.svelte";
  import { onMount } from "svelte";

  export let user: User;

  let todos = [];
  let newTaskText = "";
  let errorText = "";

  onMount(() => {
    fetchTodos();
  });

  const fetchTodos = async () => {
    let { data, error } = await supabase
      .from("todos")
      .select("*")
      .order("id", { ascending: true });
    if (error) {
      console.log("error", error);
    } else {
      todos = data;
    }
  };

  const addTodo = async (taskText) => {
    let task = taskText.trim();
    if (task.length) {
      let { data: todo, error } = await supabase
        .from("todos")
        .insert({ task, user_id: user.id })
        .single();

      if (error) {
        errorText = error.message;
      } else {
        todos = [...todos, todo];
        newTaskText = "";
      }
    }
  };

  const deleteTodo = async (id) => {
    try {
      await supabase.from("todos").delete().eq("id", id);
      todos = todos.filter((x) => x.id != id);
    } catch (error) {
      console.log("error", error);
    }
  };
</script>

<div class="w-full">
  <h1 class="mb-12">Todo List.</h1>
  <form
    on:submit|preventDefault={() => addTodo(newTaskText)}
    class="flex gap-2 my-2"
  >
    <input
      class="rounded w-full p-2"
      type="text"
      placeholder="make coffee"
      bind:value={newTaskText}
    />
    <button type="submit" class="btn-black"> Add </button>
  </form>
  {#if !!errorText}
    <Alert text={errorText} />
  {/if}
  <div class="bg-white shadow overflow-hidden rounded-md">
    <ul>
      {#each todos as todo (todo.id)}
        <Todo {todo} onDelete={() => deleteTodo(todo.id)} />
      {/each}
    </ul>
  </div>
</div>
