// apps/www/components/Realtime/Hero/Cursor.tsx
import { memo } from 'react'
import { MousePointer2 } from 'lucide-react'
import { cn } from 'ui'

function CursorInner({
  className,
  style,
  color,
  name,
}: {
  className?: string
  style?: React.CSSProperties
  color: string
  name: string
}) {
  return (
    <div className={cn('pointer-events-none', className)} style={style}>
      <MousePointer2 color={color} fill={color} size={30} />
      <div
        className="mt-1 px-2 py-1 rounded-sm text-xs font-bold text-white text-center whitespace-nowrap"
        style={{ backgroundColor: color }}
      >
        {name}
      </div>
    </div>
  )
}

export const Cursor = memo(CursorInner)

// blocks/vue/registry/default/realtime-cursor/vue/components/cursor.vue
<script setup lang="ts">
import { MousePointer2 } from 'lucide-vue-next'
import { cn } from '@/lib/utils'
import type { CSSProperties } from 'vue'

defineProps<{
  className?: string
  style?: CSSProperties
  color: string
  name: string
}>()
</script>

<template>
  <div
    :class="cn('pointer-events-none', className)"
    :style="style"
  >
    <MousePointer2
      :color="color"
      :fill="color"
      :size="30"
    />

    <div
      class="mt-1 px-2 py-1 rounded text-xs font-bold text-white text-center"
      :style="{ backgroundColor: color }"
    >
      {{ name }}
    </div>
  </div>
</template>
