// apps/ui-library/registry/default/blocks/realtime-cursor/components/realtime-cursors.tsx
'use client'

import { Cursor } from '../components/cursor'
import { useRealtimeCursors } from '../hooks/use-realtime-cursors'

const THROTTLE_MS = 50

export const RealtimeCursors = ({ roomName, username }: { roomName: string; username: string }) => {
  const { cursors } = useRealtimeCursors({ roomName, username, throttleMs: THROTTLE_MS })

  return (
    <div>
      {Object.keys(cursors).map((id) => (
        <Cursor
          key={id}
          className="fixed transition-transform ease-in-out z-50"
          style={{
            transitionDuration: '20ms',
            top: 0,
            left: 0,
            transform: `translate(${cursors[id].position.x}px, ${cursors[id].position.y}px)`,
          }}
          color={cursors[id].color}
          name={cursors[id].user.name}
        />
      ))}
    </div>
  )
}

// blocks/vue/registry/default/realtime-cursor/vue/components/realtime-cursors.vue
<script setup lang="ts">
import { Cursor } from '@/components/cursor'
import { useRealtimeCursors } from '@/composables/useRealtimeCursors'

const THROTTLE_MS = 50

const props = defineProps<{
  roomName: string
  username: string
}>()

const { cursors } = useRealtimeCursors({
  roomName: props.roomName,
  username: props.username,
  throttleMs: THROTTLE_MS,
})
</script>

<template>
  <div>
    <Cursor
      v-for="(cursor, id) in cursors"
      :key="id"
      className="fixed transition-transform ease-in-out z-50"
      :style="{
        transitionDuration: '20ms',
        top: '0px',
        left: '0px',
        transform: `translate(${cursor.position.x}px, ${cursor.position.y}px)`,
      }"
      :color="cursor.color"
      :name="cursor.user.name"
    />
  </div>
</template>
