// apps/ui-library/registry/default/blocks/passwordless-auth-react-router/app/routes/protected.tsx
import { createClient } from '@/registry/default/clients/react-router/lib/supabase/server'
import { Button } from '@/registry/default/components/ui/button'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/registry/default/components/ui/card'
import { type LoaderFunctionArgs, redirect, useLoaderData } from 'react-router'

export const loader = async ({ request }: LoaderFunctionArgs) => {
  const { supabase } = createClient(request)

  const { data, error } = await supabase.auth.getUser()
  if (error || !data?.user) {
    return redirect('/passwordless')
  }

  return data
}

export default function ProtectedPage() {
  let data = useLoaderData<typeof loader>()

  return (
    <div className="flex min-h-svh w-full items-center justify-center p-6 md:p-10">
      <div className="w-full max-w-sm">
        <Card>
          <CardHeader>
            <CardTitle className="text-2xl">Protected Page</CardTitle>
            <CardDescription>You are logged in</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="flex flex-col gap-4">
              <div className="rounded-lg border p-4">
                <p className="text-sm font-medium">Email</p>
                <p className="text-sm text-muted-foreground">{data.user.email}</p>
              </div>
              <div className="rounded-lg border p-4">
                <p className="text-sm font-medium">User ID</p>
                <p className="text-sm text-muted-foreground">{data.user.id}</p>
              </div>
              <form method="post" action="/logout">
                <Button type="submit" variant="outline" className="w-full">
                  Sign out
                </Button>
              </form>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}

// blocks/vue/registry/default/password-based-auth/nuxtjs/app/pages/protected/index.vue
<script setup lang="ts">
import { onMounted, ref } from "vue"
import { useRouter } from "vue-router"
import { createClient } from "@/lib/supabase/client"

const router = useRouter()
const supabase = createClient()
const email = ref<string | null>(null)
const loading = ref(true)

onMounted(async () => {
  const { data, error } = await supabase.auth.getUser()

  if (error || !data?.user) {
    router.replace("/auth/login")
    return
  }

  email.value = data.user.email
  loading.value = false
})

const handleLogout = async () => {
  await supabase.auth.signOut()
  router.replace("/auth/login")
}
</script>

<template>
  <div class="flex h-screen w-full items-center justify-center">
    <div v-if="loading" class="text-muted-foreground">Checking authentication...</div>

    <div v-else class="flex items-center gap-2">
      <p>
        Hello <span class="font-semibold">{{ email }}</span>
      </p>
      <button
        class="rounded-md bg-primary text-primary-foreground px-3 py-2 text-sm font-medium hover:bg-primary/90"
        @click="handleLogout"
      >
        Sign out
      </button>
    </div>
  </div>
</template>
