// blocks/vue/registry/default/realtime-chat/vue/components/realtime-chat.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { Send } from 'lucide-vue-next'

import ChatMessageItem from './chat-message-item.vue'
import { useChatScroll } from '../composables/useChatScroll'
import {
  useRealtimeChat,
  type ChatMessage,
} from '../composables/useRealtimeChat'
  // @ts-ignore
import Button from '@/components/ui/Button.vue'
  // @ts-ignore
import Input from '@/components/ui/Input.vue'

interface RealtimeChatProps {
  roomName: string
  username: string
  onMessage?: (messages: ChatMessage[]) => void
  messages?: ChatMessage[]
}

const props = defineProps<RealtimeChatProps>()

const initialMessages = computed(() => props.messages ?? [])

const { containerRef, scrollToBottom } = useChatScroll()

const { messages: realtimeMessages, sendMessage, isConnected } =
  useRealtimeChat({
    roomName: props.roomName,
    username: props.username,
  })

const newMessage = ref('')

/**
 * Merge + dedupe + sort
 */
const allMessages = computed<ChatMessage[]>(() => {
  const merged = [...initialMessages.value, ...realtimeMessages.value]

  const unique = merged.filter(
    (message, index, self) =>
      index === self.findIndex((m) => m.id === message.id)
  )

  return unique.sort((a, b) =>
    a.createdAt.localeCompare(b.createdAt)
  )
})

/**
 * Emit messages to parent if callback provided
 */
watch(allMessages, (messages) => {
  if (props.onMessage) {
    props.onMessage(messages)
  }

  scrollToBottom()
}, { flush: 'post' })

function handleSendMessage() {
  if (!newMessage.value.trim() || !isConnected.value) return

  sendMessage(newMessage.value)
  newMessage.value = ''
}
</script>

<template>
  <div class="flex flex-col h-full w-full bg-background text-foreground antialiased">
    <!-- Messages -->
    <div
      ref="containerRef"
      role="log"
      aria-label="Chat messages"
      aria-live="polite"
      class="flex-1 overflow-y-auto p-4 space-y-4"
    >
      <div
        v-if="allMessages.length === 0"
        class="text-center text-sm text-muted-foreground"
      >
        No messages yet. Start the conversation!
      </div>

      <div class="space-y-1">
        <div
          v-for="(message, index) in allMessages"
          :key="message.id"
          class="animate-in fade-in slide-in-from-bottom-4 duration-300"
        >
          <ChatMessageItem
            :message="message"
            :isOwnMessage="message.user.name === props.username"
            :showHeader="
              !allMessages[index - 1] ||
              allMessages[index - 1].user.name !== message.user.name
            "
          />
        </div>
      </div>
    </div>

    <!-- Input -->
    <form
      @submit.prevent="handleSendMessage"
      class="flex w-full gap-2 border-t border-border p-4"
    >
      <Input
        v-model="newMessage"
        :disabled="!isConnected"
        type="text"
        placeholder="Type a message..."
        aria-label="Message"
        :class="[
          'rounded-full bg-background text-sm transition-all duration-300',
          isConnected && newMessage.trim()
            ? 'w-[calc(100%-36px)]'
            : 'w-full',
        ]"
      />

      <Button
        v-if="isConnected && newMessage.trim()"
        type="submit"
        :disabled="!isConnected"
        aria-label="Send message"
        class="aspect-square rounded-full animate-in fade-in slide-in-from-right-4 duration-300"
      >
        <Send class="size-4" aria-hidden="true" />
      </Button>
    </form>
  </div>
</template>

// apps/ui-library/registry/default/blocks/realtime-chat/components/realtime-chat.tsx
'use client'

import { Send } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'

import { cn } from '@/lib/utils'
import { ChatMessageItem } from '@/registry/default/blocks/realtime-chat/components/chat-message'
import { useChatScroll } from '@/registry/default/blocks/realtime-chat/hooks/use-chat-scroll'
import {
  useRealtimeChat,
  type ChatMessage,
} from '@/registry/default/blocks/realtime-chat/hooks/use-realtime-chat'
import { Button } from '@/registry/default/components/ui/button'
import { Input } from '@/registry/default/components/ui/input'

interface RealtimeChatProps {
  roomName: string
  username: string
  onMessage?: (messages: ChatMessage[]) => void
  messages?: ChatMessage[]
}

/**
 * Realtime chat component
 * @param roomName - The name of the room to join. Each room is a unique chat.
 * @param username - The username of the user
 * @param onMessage - The callback function to handle the messages. Useful if you want to store the messages in a database.
 * @param messages - The messages to display in the chat. Useful if you want to display messages from a database.
 * @returns The chat component
 */
export const RealtimeChat = ({
  roomName,
  username,
  onMessage,
  messages: initialMessages = [],
}: RealtimeChatProps) => {
  const { containerRef, scrollToBottom } = useChatScroll()

  const {
    messages: realtimeMessages,
    sendMessage,
    isConnected,
  } = useRealtimeChat({
    roomName,
    username,
  })
  const [newMessage, setNewMessage] = useState('')

  // Merge realtime messages with initial messages
  const allMessages = useMemo(() => {
    const mergedMessages = [...initialMessages, ...realtimeMessages]
    // Remove duplicates based on message id
    const uniqueMessages = mergedMessages.filter(
      (message, index, self) => index === self.findIndex((m) => m.id === message.id)
    )
    // Sort by creation date
    const sortedMessages = uniqueMessages.sort((a, b) => a.createdAt.localeCompare(b.createdAt))

    return sortedMessages
  }, [initialMessages, realtimeMessages])

  useEffect(() => {
    if (onMessage) {
      onMessage(allMessages)
    }
  }, [allMessages, onMessage])

  useEffect(() => {
    // Scroll to bottom whenever messages change
    scrollToBottom()
  }, [allMessages, scrollToBottom])

  const handleSendMessage = useCallback(
    (e: React.FormEvent) => {
      e.preventDefault()
      if (!newMessage.trim() || !isConnected) return

      sendMessage(newMessage)
      setNewMessage('')
    },
    [newMessage, isConnected, sendMessage]
  )

  return (
    <div className="flex flex-col h-full w-full bg-background text-foreground antialiased">
      {/* Messages */}
      <div
        ref={containerRef}
        role="log"
        aria-label="Chat messages"
        aria-live="polite"
        className="flex-1 overflow-y-auto p-4 space-y-4"
      >
        {allMessages.length === 0 ? (
          <div className="text-center text-sm text-muted-foreground">
            No messages yet. Start the conversation!
          </div>
        ) : null}
        <div className="space-y-1">
          {allMessages.map((message, index) => {
            const prevMessage = index > 0 ? allMessages[index - 1] : null
            const showHeader = !prevMessage || prevMessage.user.name !== message.user.name

            return (
              <div
                key={message.id}
                className="animate-in fade-in slide-in-from-bottom-4 duration-300"
              >
                <ChatMessageItem
                  message={message}
                  isOwnMessage={message.user.name === username}
                  showHeader={showHeader}
                />
              </div>
            )
          })}
        </div>
      </div>

      <form onSubmit={handleSendMessage} className="flex w-full gap-2 border-t border-border p-4">
        <Input
          className={cn(
            'rounded-full bg-background text-sm transition-all duration-300',
            isConnected && newMessage.trim() ? 'w-[calc(100%-36px)]' : 'w-full'
          )}
          type="text"
          value={newMessage}
          onChange={(e) => setNewMessage(e.target.value)}
          placeholder="Type a message..."
          aria-label="Message"
          disabled={!isConnected}
        />
        {isConnected && newMessage.trim() && (
          <Button
            className="aspect-square rounded-full animate-in fade-in slide-in-from-right-4 duration-300"
            type="submit"
            aria-label="Send message"
            disabled={!isConnected}
          >
            <Send className="size-4" aria-hidden="true" />
          </Button>
        )}
      </form>
    </div>
  )
}
