// blocks/vue/registry/default/social-auth/nuxtjs/app/pages/auth/error.vue
<script setup lang="ts">
import { useRoute } from "vue-router"
import { computed } from "vue"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

const route = useRoute()
const errorMessage = computed(() => route.query.error as string || null)
</script>

<template>
  <div class="flex min-h-screen w-full items-center justify-center p-6 md:p-10">
    <div class="w-full max-w-sm">
      <div class="flex flex-col gap-6">
        <Card>
          <CardHeader>
            <CardTitle class="text-2xl">Sorry, something went wrong.</CardTitle>
          </CardHeader>
          <CardContent>
            <p v-if="errorMessage" class="text-sm text-muted-foreground">
              Code error: {{ errorMessage }}
            </p>
            <p v-else class="text-sm text-muted-foreground">
              An unspecified error occurred.
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  </div>
</template>

// apps/ui-library/registry/default/blocks/social-auth-nextjs/app/auth/error/page.tsx
import { Card, CardContent, CardHeader, CardTitle } from '@/registry/default/components/ui/card'

export default async function Page({ searchParams }: { searchParams: Promise<{ error: string }> }) {
  const params = await searchParams

  return (
    <div className="flex min-h-svh w-full items-center justify-center p-6 md:p-10">
      <div className="w-full max-w-sm">
        <div className="flex flex-col gap-6">
          <Card>
            <CardHeader>
              <CardTitle className="font-medium text-lg tracking-normal">Sorry, something went wrong.</CardTitle>
            </CardHeader>
            <CardContent>
              {params?.error ? (
                <p className="text-sm text-muted-foreground">Code error: {params.error}</p>
              ) : (
                <p className="text-sm text-muted-foreground">An unspecified error occurred.</p>
              )}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
