// packages/ui/src/components/shadcn/label.tsx
import * as React from 'react'
import * as LabelPrimitive from '@radix-ui/react-label'
import { VariantProps, cva } from 'class-variance-authority'

import { cn } from '@ui/lib/utils'

const labelVariants = cva(
  'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70'
)

const Label = React.forwardRef<
  React.ElementRef<typeof LabelPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof LabelPrimitive.Root> & VariantProps<typeof labelVariants>
>(({ className, ...props }, ref) => (
  <LabelPrimitive.Root ref={ref} className={cn(labelVariants(), className)} {...props} />
))
Label.displayName = LabelPrimitive.Root.displayName

export { Label }

// blocks/vue/registry/default/components/ui/Label.vue
<script setup lang="ts">
import { cva, type VariantProps } from "class-variance-authority"
import { cn } from "../../lib/utils"

const labelVariants = cva(
  "text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
)

type LabelVariants = VariantProps<typeof labelVariants>

defineProps<{
  as?: string
  class?: string
}>()

const props = defineProps({
  as: { type: String, default: "label" },
  class: { type: String, default: "" },
})

const labelClass = cn(labelVariants(), props.class)
</script>

<template>
  <component :is="as" :class="labelClass">
    <slot />
  </component>
</template>
