// examples/user-management/nuxtjs-user-management/components/Account.vue
<template>
  <div class="account">
    <div>
      <label for="email">Email</label>
      <input id="email" type="text" v-model="state.propSession.user.email" disabled />
    </div>
    <div>
      <label for="username">Username</label>
      <input id="username" type="text" v-model="state.username" />
    </div>
    <div>
      <label for="website">Website</label>
      <input id="website" type="website" v-model="state.website" />
    </div>

    <div>
      <button class="button block primary" @click="updateProfile" :disabled="state.loading">
        {{ state.loading ? 'Loading ...' : 'Update' }}
      </button>
    </div>

    <div>
      <button @click="signOut" class="button block">Sign Out</button>
    </div>
  </div>
</template>

<script>
import { supabase } from '../lib/supabaseClient'
export default {
  props: ['session'],
  data() {
    return {
      state: {
        loading: true,
        username: '',
        website: '',
        propSession: this.session,
      },
    }
  },
  mounted() {
    this.getProfile()
  },
  methods: {
    async signOut() {
      const { error } = await supabase.auth.signOut()
      if (error) console.log('Error logging out:', error.message)
    },

    setProfile(profile) {
      this.state.username = profile.username
      this.state.website = profile.website
    },

    async getProfile() {
      try {
        this.state.loading = true

        const { data, error } = await supabase
          .from('profiles')
          .select(`username, website, avatar_url`)
          .eq('id', this.state.propSession.user.id)
          .single()

        if (error || !data) {
          throw error || new Error('Profile not found')
        }

        this.setProfile(data)
      } catch (error) {
        console.log('error', error.message)
      } finally {
        this.state.loading = false
      }
    },

    async updateProfile() {
      try {
        this.state.loading = true

        const updates = {
          id: this.state.propSession.user.id,
          username: this.state.username,
          website: this.state.website,
          updated_at: new Date(),
        }

        const { error } = await supabase.from('profiles').upsert(updates)

        if (error) {
          throw error
        }
      } catch (error) {
        alert(error.message)
      } finally {
        this.state.loading = false
      }
    },
  },
}
</script>

// examples/nextjs-ts-user-managment/components/Account.tsx
import { useState, useEffect } from 'react'
import { supabase } from '../lib/supabaseClient'
import { Profile } from '../lib/constants'
import { AuthSession } from '@supabase/supabase-js'

export default function Account({ session }: { session: AuthSession }) {
  const [loading, setLoading] = useState<boolean>(true)
  const [username, setUsername] = useState<string | null>(null)
  const [website, setWebsite] = useState<string | null>(null)

  useEffect(() => {
    getProfile()
  }, [session])

  async function signOut() {
    const { error } = await supabase.auth.signOut()
    if (error) console.log('Error logging out:', error.message)
  }

  function setProfile(profile: Profile) {
    setUsername(profile.username)
    setWebsite(profile.website)
  }

  async function getProfile() {
    try {
      setLoading(true)

      let { data, error } = await supabase
        .from<Profile>('profiles')
        .select(`username, website, avatar_url`)
        .eq('id', session.user.id)
        .single()

      if (error || !data) {
        throw error || new Error('Profile not found')
      }

      setProfile(data)
    } catch (error) {
      console.log('error', error.message)
    } finally {
      setLoading(false)
    }
  }

  async function updateProfile() {
    try {
      setLoading(true)

      const updates = {
        id: session.user.id,
        username,
        website,
        updated_at: new Date(),
      }

      let { error } = await supabase.from('profiles').upsert(updates, {
        returning: 'minimal', // Don't return the value after inserting
      })

      if (error) {
        throw error
      }
    } catch (error) {
      alert(error.message)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div
      style={{
        minWidth: 250,
        maxWidth: 600,
        margin: 'auto',
        display: 'flex',
        flexDirection: 'column',
        gap: 20,
      }}
    >
      <div>
        <label htmlFor="email">Email</label>
        <input id="email" type="text" value={session.user.email} disabled />
      </div>
      <div>
        <label htmlFor="username">Username</label>
        <input
          id="username"
          type="text"
          value={username || ''}
          onChange={(e) => setUsername(e.target.value)}
        />
      </div>
      <div>
        <label htmlFor="website">Website</label>
        <input
          id="website"
          type="website"
          value={website || ''}
          onChange={(e) => setWebsite(e.target.value)}
        />
      </div>

      <div>
        <button className="button block primary" onClick={() => updateProfile()} disabled={loading}>
          {loading ? 'Loading ...' : 'Update'}
        </button>
      </div>

      <div>
        <button className="button block" onClick={() => signOut()}>
          Sign Out
        </button>
      </div>
    </div>
  )
}
