// examples/nextjs-ts-user-management/components/ProfileCard.tsx
import { Profile } from '../lib/constants'

export default function ProfileCard({ profile }: { profile: Profile }) {
  const lastUpdated = profile.updated_at ? new Date(profile.updated_at) : null
  return (
    <div className="card">
      <p>Username: {profile.username}</p>
      <p>Website: {profile.website}</p>
      <p>Avatar: {profile.avatar_url}</p>
      <p>
        <small>
          Last updated{' '}
          {lastUpdated
            ? `${lastUpdated.toLocaleDateString()} ${lastUpdated.toLocaleTimeString()}`
            : 'Never'}
        </small>
      </p>
    </div>
  )
}

// examples/nuxtjs-user-management/components/ProfileCard.vue
<template>
  <div className="card">
    <p>Username: {{ state.propProfile.username }}</p>
    <p>Website: {{ state.propProfile.website }}</p>
    <p>
      <small>
        Last updated
        {{
          state.lastUpdated
            ? `${state.lastUpdated.toLocaleDateString()}
        ${state.lastUpdated.toLocaleTimeString()}`
            : "Never"
        }}
      </small>
    </p>
  </div>
</template>

<script>
export default {
  props: ["profile"],
  data() {
    return {
      state: {
        propProfile: this.profile,
        lastUpdated: this.profile.updated_at
          ? new Date(this.profile.updated_at)
          : null,
      },
    };
  },
};
</script>
