// examples/supabase-js-v1/user-management/nuxtjs-user-management/components/ProfileCard.vue
<template>
  <div class="profileCard">
    <div class="userInfo">
      <p class="username">{{ state.propProfile.username }}</p>
      <p class="website">{{ state.propProfile.website }}</p>
      <p>
        <small>
          Last updated
          {{
            state.lastUpdated
              ? `${state.lastUpdated.toLocaleDateString()}
          ${state.lastUpdated.toLocaleTimeString()}`
              : "Never"
          }}
        </small>
      </p>
    </div>
  </div>
</template>

<script>
export default {
  props: ["profile"],
  data() {
    return {
      state: {
        propProfile: this.profile,
        lastUpdated: this.profile.updated_at
          ? new Date(this.profile.updated_at)
          : null,
      },
    };
  },
};
</script>

// examples/user-management/nextjs-ts-user-management/components/ProfileCard.tsx
import { Profile } from '../lib/constants'
import Avatar from './Avatar'

export default function ProfileCard({ profile }: { profile: Profile }) {
  const lastUpdated = profile.updated_at ? new Date(profile.updated_at) : null
  return (
    <div className="profileCard">
      <Avatar url={profile.avatar_url} size={100} />
      <div className="userInfo">
        <p className="username">{profile.username}</p>
        <a className="website" href={profile.website} target="_blank">
          {profile.website}
        </a>
        <p>
          <small>
            Last updated{' '}
            {lastUpdated
              ? `${lastUpdated.toLocaleDateString()} ${lastUpdated.toLocaleTimeString()}`
              : 'Never'}
          </small>
        </p>
      </div>
      <div />
    </div>
  )
}
