// blocks/vue/registry/default/realtime-avatar-stack/vue/components/avatar-stack.vue
<script setup lang="ts">
import { computed } from 'vue'

import Avatar from '@/components/ui/avatar/Avatar.vue'
import AvatarImage from '@/components/ui/avatar/AvatarImage.vue'
import AvatarFallback from '@/components/ui/avatar/AvatarFallback.vue'

import Tooltip from '@/components/ui/tooltip/Tooltip.vue'
import TooltipContent from '@/components/ui/tooltip/TooltipContent.vue'
import TooltipTrigger from '@/components/ui/tooltip/TooltipTrigger.vue'

interface AvatarItem {
  name: string
  image: string
}

const props = defineProps<{
  avatars: AvatarItem[]
  orientation?: 'vertical' | 'horizontal'
  maxAvatarsAmount?: number
  class?: string
}>()

const orientation = computed(() => props.orientation ?? 'vertical')
const maxAvatarsAmount = computed(() => props.maxAvatarsAmount ?? 3)

const shownAvatars = computed(() =>
  props.avatars.slice(0, maxAvatarsAmount.value)
)

const hiddenAvatars = computed(() =>
  props.avatars.slice(maxAvatarsAmount.value)
)

const containerClasses = computed(() => [
  'flex -space-x-4 -space-y-4',
  orientation.value === 'vertical' ? 'flex-row -space-y-0' : 'flex-col -space-x-0',
  props.class,
])

function getInitials(name: string) {
  return name
    ?.split(' ')
    ?.map(word => word[0])
    ?.join('')
    ?.toUpperCase()
}
</script>

<template>
  <div :class="containerClasses">
    <!-- Visible avatars -->
    <Tooltip
      v-for="({ name, image }, index) in shownAvatars"
      :key="`${name}-${image}-${index}`"
    >
      <TooltipTrigger>
        <Avatar class="hover:z-10">
          <AvatarImage :src="image" />
          <AvatarFallback>
            {{ getInitials(name) }}
          </AvatarFallback>
        </Avatar>
      </TooltipTrigger>

      <TooltipContent>
        <p>{{ name }}</p>
      </TooltipContent>
    </Tooltip>

    <!-- Hidden avatars -->
    <Tooltip v-if="hiddenAvatars.length">
      <TooltipTrigger>
        <Avatar>
          <AvatarFallback>
            +{{ avatars.length - shownAvatars.length }}
          </AvatarFallback>
        </Avatar>
      </TooltipTrigger>

      <TooltipContent>
        <p
          v-for="({ name }, index) in hiddenAvatars"
          :key="`${name}-${index}`"
        >
          {{ name }}
        </p>
      </TooltipContent>
    </Tooltip>
  </div>
</template>

// apps/ui-library/registry/default/blocks/realtime-avatar-stack/components/avatar-stack.tsx
import { cn } from '../../../../../lib/utils'
import { Avatar, AvatarFallback, AvatarImage } from '../../../components/ui/avatar'
import { Tooltip, TooltipContent, TooltipTrigger } from '../../../components/ui/tooltip'
import { cva, type VariantProps } from 'class-variance-authority'
import * as React from 'react'

const avatarStackVariants = cva('flex -space-x-4 -space-y-4', {
  variants: {
    orientation: {
      vertical: 'flex-row',
      horizontal: 'flex-col',
    },
  },
  defaultVariants: {
    orientation: 'vertical',
  },
})

export interface AvatarStackProps
  extends React.HTMLAttributes<HTMLDivElement>,
  VariantProps<typeof avatarStackVariants> {
  avatars: { name: string; image: string }[]
  maxAvatarsAmount?: number
}

const AvatarStack = ({
  className,
  orientation,
  avatars,
  maxAvatarsAmount = 3,
  ...props
}: AvatarStackProps) => {
  const shownAvatars = avatars.slice(0, maxAvatarsAmount)
  const hiddenAvatars = avatars.slice(maxAvatarsAmount)

  return (
    <div
      className={cn(
        avatarStackVariants({ orientation }),
        className,
        orientation === 'horizontal' ? '-space-x-0' : '-space-y-0'
      )}
      {...props}
    >
      {shownAvatars.map(({ name, image }, index) => (
        <Tooltip key={`${name}-${image}-${index}`}>
          <TooltipTrigger asChild>
            <Avatar className="hover:z-10">
              <AvatarImage src={image} />
              <AvatarFallback>
                {name
                  ?.split(' ')
                  ?.map((word) => word[0])
                  ?.join('')
                  ?.toUpperCase()}
              </AvatarFallback>
            </Avatar>
          </TooltipTrigger>
          <TooltipContent>
            <p>{name}</p>
          </TooltipContent>
        </Tooltip>
      ))}

      {hiddenAvatars.length ? (
        <Tooltip key="hidden-avatars">
          <TooltipTrigger asChild>
            <Avatar>
              <AvatarFallback>+{avatars.length - shownAvatars.length}</AvatarFallback>
            </Avatar>
          </TooltipTrigger>
          <TooltipContent>
            {hiddenAvatars.map(({ name }, index) => (
              <p key={`${name}-${index}`}>{name}</p>
            ))}
          </TooltipContent>
        </Tooltip>
      ) : null}
    </div>
  )
}

export { AvatarStack, avatarStackVariants }
