// blocks/vue/registry/default/realtime-avatar-stack/nuxtjs/app/components/realtime-avatar-stack.vue
<script setup lang="ts">
import { computed } from 'vue'

  // @ts-ignore
import AvatarStack from '@/components/avatar-stack.vue'
import { useRealtimePresenceRoom } from '../composables/useRealtimePresenceRoom'

const props = defineProps<{
  roomName: string
}>()

const { users: usersMap } = useRealtimePresenceRoom(props.roomName)

const avatars = computed(() =>
  Object.values(usersMap.value).map((user) => ({
    name: user.name,
    image: user.image,
  }))
)
</script>

<template>
  <AvatarStack :avatars="avatars" />
</template>

// apps/ui-library/registry/default/blocks/realtime-avatar-stack/components/realtime-avatar-stack.tsx
import { useMemo } from 'react'
import { useRealtimePresenceRoom } from '../hooks/use-realtime-presence-room'
import { AvatarStack } from './avatar-stack'

export const RealtimeAvatarStack = ({ roomName }: { roomName: string }) => {
  const { users: usersMap } = useRealtimePresenceRoom(roomName)
  const avatars = useMemo(() => {
    return Object.values(usersMap).map((user) => ({
      name: user.name,
      image: user.image,
    }))
  }, [usersMap])

  return <AvatarStack avatars={avatars} />
}
